Login Failed - 'jimmyadda'  date: 2025-07-01 11:02:01.940688
Login Failed - 'admin'  date: 2025-07-01 11:02:07.279739
New User Created: admin
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
Exception on /product/1/edit [GET]
Traceback (most recent call last):
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\app.py", line 225, in edit_product
    return render_template('edit_product.html', products=product)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\templates\edit_product.html", line 54, in template
    <a href="{{ url_for('index') }}" class="btn btn-link">חזור לדף הבית</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
Exception on /product/1/edit [GET]
Traceback (most recent call last):
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\app.py", line 226, in edit_product
    return render_template('edit_product.html', products=product,categories=categories)
                                                                            ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'categories' where it is not associated with a value
Exception on /product/1/edit [GET]
Traceback (most recent call last):
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\app.py", line 226, in edit_product
    return render_template('edit_product.html', products=product,categories=category)
                                                                            ^^^^^^^^
UnboundLocalError: cannot access local variable 'category' where it is not associated with a value
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
Exception on /product/1/edit [POST]
Traceback (most recent call last):
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\app.py", line 223, in edit_product
    ok = database_write(sql,form)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\HandelDB.py", line 19, in database_write
    row_affected = db.execute(sql, data).rowcount
                   ^^^^^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: You did not supply a value for binding parameter :Sel_category.
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
Exception on /product/1/edit [POST]
Traceback (most recent call last):
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\app.py", line 224, in edit_product
    ok = database_write(sql,form)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\HandelDB.py", line 19, in database_write
    row_affected = db.execute(sql, data).rowcount
                   ^^^^^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: You did not supply a value for binding parameter :Sel_category.
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
Exception on /product/1/edit [POST]
Traceback (most recent call last):
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\app.py", line 224, in edit_product
    ok = database_write(sql,form)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\HandelDB.py", line 19, in database_write
    row_affected = db.execute(sql, data).rowcount
                   ^^^^^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: You did not supply a value for binding parameter :Sel_category.
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
Exception on /product/6/edit [GET]
Traceback (most recent call last):
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\app.py", line 229, in edit_product
    return render_template('edit_product.html', products=product,categories=category)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\templates\edit_product.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\templates\base.html", line 76, in top-level template code
    {% block content %}
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\templates\edit_product.html", line 36, in block 'content'
    <!-- <option value="{{ cat.id }}" {% if cat.id == product.category|int %}selected{% endif %}>{{ cat.name }}</option> -->
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\filters.py", line 997, in do_int
    return int(value)
           ^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'category'
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
Exception on /product/6/edit [GET]
Traceback (most recent call last):
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\app.py", line 230, in edit_product
    return render_template('edit_product.html', products=product,categories=category)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\templates\edit_product.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\templates\base.html", line 76, in top-level template code
    {% block content %}
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\templates\edit_product.html", line 36, in block 'content'
    <!-- <option value="{{ cat.id }}" {% if cat.id == product.category|int %}selected{% endif %}>{{ cat.name }}</option> -->
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\filters.py", line 997, in do_int
    return int(value)
           ^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'category'
Exception on /product/6/edit [GET]
Traceback (most recent call last):
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\app.py", line 230, in edit_product
    return render_template('edit_product.html', products=product,categories=category)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\templates\edit_product.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\templates\base.html", line 76, in top-level template code
    {% block content %}
  File "C:\Users\ajimmy\Python\MaLiknot\WebApp\templates\edit_product.html", line 36, in block 'content'
    <!-- <option value="{{ cat.id }}" {% if cat.id == product.category|int %}selected{% endif %}>{{ cat.name }}</option> -->
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ajimmy\Python\MaLiknot\.venv\Lib\site-packages\jinja2\filters.py", line 997, in do_int
    return int(value)
           ^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'category'
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
{'userid': 'admin', 'email': 'maliknot@gmail.com', 'name': 'admin'}Has Logged in
